name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::228235827083:role/TaskManagerGitHubActionsRole
          aws-region: ap-south-1

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          docker build -t task-manager .
          docker tag task-manager:latest 228235827083.dkr.ecr.ap-south-1.amazonaws.com/task-manager:${{ github.sha }}
          docker push 228235827083.dkr.ecr.ap-south-1.amazonaws.com/task-manager:${{ github.sha }}